# Documentation Coverage Ignore List
#
# This file contains roles that should be excluded from documentation coverage checks.
# Add role names that don't need documentation (e.g., internal roles, deprecated roles, etc.)

# Saltbox roles to ignore
saltbox:
  - "authentik_worker"
  - "backup"
  - "backup2"
  - "cloudflare"
  - "cloudplow_disable"
  - "common"
  - "crowdsec"
  - "docker"
  - "docker_socket_proxy"
  - "download_clients"
  - "download_indexers"
  - "glances"
  - "hetzner"
  - "hetzner_vlan"  # covered by hetzner_nfs documentation
  - "kernel"
  - "main_tags"
  - "media_server"
  - "mount_templates"
  - "motd"
  - "notify"
  - "nvidia"
  - "permissions"
  - "plex_auth_token"
  - "plex_extra_tasks"
  - "plex_fix_futures"
  - "pre_tasks"
  - "python"
  - "rclone"
  - "reboot"
  - "remote"
  - "restore"
  - "saltbox_mod"
  - "sandbox"
  - "sanity_check"
  - "scripts"
  - "shell"
  - "sub_zero"
  - "system"
  - "traefik"
  - "traefik_file_template"
  - "traefik_template"
  - "unionfs"
  - "user"
  - "user_check"
  - "webtools"
  - "yyq"

# Sandbox roles to ignore
sandbox:
  - "main_tag"
  - "maybe_finance_worker"
  - "sanity_check"
  - "tdarr_node"
  # Deprecated roles
  - "unifi"  # deprecated
  - "hoarder"  # deprecated
  - "plex_meta_manager"  # deprecated
