# Documentation Coverage Ignore List
#
# This file contains roles that should be excluded from documentation coverage checks.
# Add role names that don't need documentation (e.g., internal roles, deprecated roles, etc.)

# Saltbox roles to ignore
saltbox:
  - "authentik_worker"
  - "backup"
  - "backup2"
  - "common"
  - "docker"
  - "docker_socket_proxy"
  - "download_clients"
  - "download_indexers"
  - "kernel"
  - "main_tags"
  - "media_server"
  - "motd"
  - "notify"
  - "nvidia"
  - "plex_auth_token"
  - "plex_extra_tasks"
  - "plex_fix_futures"
  - "python"
  - "rclone"
  - "reboot"
  - "remote"
  - "restore"
  - "saltbox_mod"
  - "sanity_check"
  - "shell"
  - "sub_zero"
  - "system"
  - "traefik"
  - "traefik_file_template"
  - "traefik_template"
  - "unionfs"
  - "user"
  - "webtools"
  - "yyq"
  # Temporary until Hetzner NFS is reworked
  - "hetzner_nfs"
  - "hetzner_vlan"

# Sandbox roles to ignore
sandbox:
  - "main_tag"
  - "maybe_finance_worker"
  - "sanity_check"
  - "tdarr_node"
