# Documentation Coverage Ignore List
#
# This file contains roles that should be excluded from documentation coverage checks.
# Add role names that don't need documentation (e.g., internal roles, deprecated roles, etc.)

# Saltbox roles to ignore
saltbox:
  - "authentik_worker"
  - "backup"
  - "backup2"
  - "common"
  - "crowdsec"
  - "docker"
  - "docker_socket_proxy"
  - "download_clients"
  - "download_indexers"
  - "kernel"
  - "main_tags"
  - "media_server"
  - "motd"
  - "notify"
  - "nvidia"
  - "plex_auth_token"
  - "plex_extra_tasks"
  - "plex_fix_futures"
  - "python"
  - "rclone"
  - "reboot"
  - "remote"
  - "restore"
  - "saltbox_mod"
  - "sanity_check"
  - "shell"
  - "sub_zero"
  - "system"
  - "traefik"
  - "traefik_file_template"
  - "traefik_template"
  - "unionfs"
  - "user"
  - "webtools"
  - "yyq"

# Sandbox roles to ignore
sandbox:
  - "main_tag"
  - "maybe_finance_worker"
  - "sanity_check"
  - "tdarr_node"
  # Role names use underscores but docs pages use hyphens
  - "qbit_manage"  # docs page is qbit-manage
  - "your_spotify"  # docs page is yourspotify
  - "uptime_kuma"  # docs page is uptime-kuma
  - "unifi_network_application"  # docs page is unifi-network-application
  - "traefik_robotstxt"  # docs page is traefik-robotstxt
  - "paperless_ngx"  # docs page is paperless-ngx
  - "plex_auto_languages"  # docs page is plex-auto-languages
  - "node_red"  # docs page is node-red
  - "minecraft_bedrock"  # docs page is minecraft-bedrock
  - "invoiceninjav5"  # docs page is invoiceninja
  - "code_server"  # docs page is code-server
  - "calibre_web"  # docs page is calibre-web
  - "a_train"  # docs page is a-train
