# Apps to ignore when checking for inventory section coverage
# Add apps here that don't need inventory sections (e.g., meta pages, deprecated apps)

saltbox:
  - asshama
  - btop
  - btrfsmaintenance
  - cloudplow
  - ctop
  - custom
  - ddclient
  - diag
  - hetzner_nfs
  - iperf3
  - mainline
  - node_exporter
  - subliminal

sandbox:
  - epms
  - kcptun_client
  - kcptun_server
  - plex_dupefinder
  - plex_patrol
  - python_plexlibrary
  - varken
