name: Check Documentation Coverage

on:
  workflow_dispatch:
    inputs:
      saltbox_branch:
        description: 'Saltbox branch to check'
        required: false
        default: 'role-refactor'
      sandbox_branch:
        description: 'Sandbox branch to check'
        required: false
        default: 'role-refactor'
  push:
    branches:
      - role-refactor
    paths:
      - 'docs/apps/**'
      - 'docs/sandbox/apps/**'
      - '.docs-coverage-ignore.yml'
      - 'scripts/check-docs-coverage.py'

jobs:
  check-docs-coverage:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v5
        with:
          path: docs
          fetch-depth: 0

      - name: Checkout Saltbox repository
        uses: actions/checkout@v5
        with:
          repository: saltyorg/Saltbox
          ref: ${{ github.event.inputs.saltbox_branch || 'role-refactor' }}
          path: saltbox
          fetch-depth: 0

      - name: Checkout Sandbox repository
        uses: actions/checkout@v5
        with:
          repository: saltyorg/Sandbox
          ref: ${{ github.event.inputs.sandbox_branch || 'role-refactor' }}
          path: sandbox
          fetch-depth: 0

      - name: Setup Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Check documentation coverage
        id: coverage
        continue-on-error: true
        run: |
          cd docs
          chmod +x scripts/check-docs-coverage.py
          python3 scripts/check-docs-coverage.py
        env:
          GITHUB_WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Handle GitHub issue
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const action = ${{ toJSON(steps.coverage.outputs.action) }};

            if (action === 'create_or_update_issue') {
              const title = ${{ toJSON(steps.coverage.outputs.issue_title) }};
              const body = ${{ toJSON(steps.coverage.outputs.issue_body) }};

              // Check if an issue already exists
              const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'github-actions-docs'
              });

              const existingIssue = issues.data.find(issue =>
                issue.title.startsWith('📝 Missing documentation for')
              );

              if (existingIssue) {
                // Update existing issue
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: existingIssue.number,
                  title: title,
                  body: body
                });
                console.log(`Updated issue #${existingIssue.number}`);
              } else {
                // Create new issue
                const newIssue = await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: title,
                  body: body,
                  labels: ['github-actions-docs']
                });
                console.log(`Created issue #${newIssue.data.number}`);
              }
            } else if (action === 'close_issue') {
              const closeMessage = ${{ toJSON(steps.coverage.outputs.close_message) }};

              // Find and close any open documentation coverage issues
              const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                labels: 'github-actions-docs'
              });

              const docIssue = issues.data.find(issue =>
                issue.title.startsWith('📝 Missing documentation for')
              );

              if (docIssue) {
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: docIssue.number,
                  state: 'closed'
                });

                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: docIssue.number,
                  body: closeMessage
                });

                console.log(`Closed issue #${docIssue.number}`);
              }
            } else {
              console.log('No action needed');
            }
