name: Notify

on:
  workflow_run:
    workflows: ["Build & Deploy", "Build PR & Deploy"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  notify:
    if: contains(fromJSON('["success", "failure", "timed_out", "startup_failure", "cancelled"]'), github.event.workflow_run.conclusion)
    runs-on: ubuntu-24.04
    steps:
      - name: Notify workflow completion
        uses: saltyorg/github-actions/notify@b7feda22310aeb973e817c1b8c1911f5041e69ef # v1.0.0
        with:
          github-token: ${{ github.token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
